In [14]:
from pytrends.request import TrendReq   # 구글트렌드 데이터 가져오는 라이브러리

In [15]:
pytrends = TrendReq(hl='ko', tz = 540)  # h1- 언어, tz- timezone(분단위설정) 우리나라 GMT+9(9시간을 분으로)

In [16]:
keywords = ['sklearn', 'tensorflow', 'pytorch']

| 파라미터 | 설명 |
|---|---|
| `cat` | 카테고리. `0`인 경우 전체. 자세한 항목은 `pytrends.categories()`의 결과를 참고 |
| `timeframe` | 검색 시작일, 검색 종료일 |
| `geo` | 검색 지역 |
| `gprop` | 이미지, 뉴스, 유튜브, froogle(구글쇼핑)으로 세분화 할 경우 설정. 기본값은 그냥 구글 검색 |

In [17]:
pytrends.build_payload(keywords, cat=0, timeframe= '2023-01-01 2023-12-15', geo='KR', gprop = '')

In [19]:
data = pytrends.interest_over_time()
data

            sklearn  tensorflow  pytorch  isPartial
date
2023-01-01       16          43       93      False
2023-01-08       20          42       95      False
2023-01-15       16          45       90      False
2023-01-22       12          25       59      False
2023-01-29       17          43       99      False
2023-02-05       16          43       93      False
2023-02-12       16          39       92      False
2023-02-19       17          44      100      False
2023-02-26       11          38       77      False
2023-03-05       16          41       89      False
2023-03-12       17          39       88      False
2023-03-19       19          40       99      False
2023-03-26       21          36       90      False
2023-04-02       21          35       90      False
2023-04-09       20          38       87      False
2023-04-16       15          37       81      False
2023-04-23       18          36       86      False
2023-04-30       15          26       69      False
2023-05-07       17          38       86      False
2023-05-14       15          34       79      False
2023-05-21       17          34       72      False
2023-05-28       17          34       71      False
2023-06-04       11          27       66      False
2023-06-11       13          29       75      False
2023-06-18       17          28       63      False
2023-06-25       13          25       57      False
2023-07-02       11          23       66      False
2023-07-09       14          34       74      False
2023-07-16       16          29       75      False
2023-07-23       10          29       77      False
2023-07-30       13          25       66      False
2023-08-06       13          31       65      False
2023-08-13        9          27       60      False
2023-08-20       14          28       66      False
2023-08-27       12          23       51      False
2023-09-03       13          25       67      False
2023-09-10       11          31       70      False
2023-09-17       10          31       70      False
2023-09-24       11          25       45      False
2023-10-01       12          21       53      False
2023-10-08       15          22       60      False
2023-10-15       18          25       54      False
2023-10-22       13          31       65      False
2023-10-29       14          28       67      False
2023-11-05       13          32       63      False
2023-11-12       14          33       66      False
2023-11-19       16          30       72      False
2023-11-26       12          37       76      False
2023-12-03       12          33       63      False
2023-12-10       10          20       50       True

In [20]:
pytrends.interest_by_region(
    resolution='country',   # 시, 나라, 등 지역레벨로 설정 가능
    inc_low_vol=True,  # 검색량 적은 지역 포함
    inc_geo_code=True # 국가명과 iso코드 
)

        geoCode  sklearn  tensorflow  pytorch
geoName
강원도       KR-42       13          33       54
경기도       KR-41       12          29       59
경상남도      KR-48       10          44       46
경상북도      KR-47       11          26       63
광주광역시     KR-29       12          32       56
대구광역시     KR-27       13          25       62
대전광역시     KR-30        9          21       70
부산광역시     KR-26       13          37       50
서울특별시     KR-11       12          22       66
울산광역시     KR-31       17          21       62
인천광역시     KR-28       11          30       59
전라남도      KR-46       12          19       69
전라북도      KR-45       19          31       50
제주특별자치도   KR-49        0          39       61
충청남도      KR-44       15          39       46
충청북도      KR-43       14          30       56